<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="maxwell">

  <xacro:property name="arm_height" value="0.6604"/> <!-- deck to arm_link at max height-->
  <xacro:property name="column_height" value="1.172775" /> <!-- deck to top of 80/20 -->
  
  <xacro:include filename="$(find maxwell)/urdf/hardware/ax12.xacro" />
  <xacro:include filename="$(find maxwell)/urdf/hardware/rx64.xacro" />
  <xacro:include filename="$(find maxwell)/urdf/sensors/xtion_camera.xacro" />
  
  <!-- The following included files set up definitions of parts of the robot body -->
  <xacro:include filename="$(find maxwell)/urdf/base.urdf.xacro" />
  <xacro:include filename="$(find maxwell)/urdf/torso.urdf.xacro" />
  <xacro:include filename="$(find maxwell)/urdf/arm.urdf.xacro" />
  <xacro:include filename="$(find maxwell)/urdf/gripper.urdf.xacro" />
  <xacro:include filename="$(find maxwell)/urdf/parallel_gripper.urdf.xacro" />
  <xacro:include filename="$(find maxwell)/urdf/head.urdf.xacro" />
  <xacro:include filename="$(find maxwell)/urdf/materials.urdf.xacro" />

  <!-- Now we can start using the macros included above to define the actual Maxwell -->
  <xacro:armadillo_base name="base" color="Orange"/>

  <!-- Add Torso Upright -->
  <xacro:maxwell_torso name="torso" parent="base_link">
    <origin xyz="-0.00635 0 ${base_size_z+arm_height}" rpy="0 0 0"/>
  </xacro:maxwell_torso>

  <!-- Live joint between torso and arm -->
  <joint name="arm_lift_joint" type="prismatic">
    <axis xyz="0 0 1" />
    <limit lower="-0.464" upper="0" effort="30" velocity="0.0508"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="torso_link"/>
    <child link="arm_lift_link"/>
  </joint>
  <link name="arm_lift_link"/>

  <!-- Arm -->
  <xacro:maxwell_arm name="arm" parent="arm_lift_link">
    <origin xyz="0.0611 0 0" rpy="0 0 0"/>
  </xacro:maxwell_arm>

  <!-- New Parallel Gripper -->
  <xacro:maxwell_parallel_gripper name="gripper" parent="arm_wrist_roll" color="Orange">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:maxwell_parallel_gripper>

  <!-- Head -->
  <xacro:maxwell_head name="head" parent="torso_link" color="Orange">
    <origin xyz="0 0 ${column_height-arm_height}" rpy="0 0 0"/>
  </xacro:maxwell_head>
  <xacro:xtion_camera name="head_camera" parent="head_tilt_link">
    <origin xyz="0 0 0.026" rpy="0 0 0"/>
  </xacro:xtion_camera>

</robot>
