<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="maxwell_torso" params="name parent *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 ${column_height/2 - arm_height}" rpy="0 0 0 " />
        <geometry>
          <box size="0.0254 0.0254 ${column_height}"/>
        </geometry>
        <material name="Grey" />
      </visual>
      <collision>
        <origin xyz="0 0 ${column_height/2 - arm_height}" rpy="0 0 0 " />
        <geometry>
          <box size="0.0254 0.0254 ${column_height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_actuator_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_actuator_link"/>
    </joint>
    <link name="${name}_actuator_link">
      <visual>
        <origin xyz="-0.05 -0.0127 -0.560" rpy="0 0 3.14" />
        <geometry>
          <mesh filename="package://maxwell/meshes/FA-35-TR.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <origin xyz="-0.03 0 ${-0.650/2+.08}" rpy="0 0 0 " />
        <geometry>
          <box size="0.03 0.0254 0.650"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>

</robot>
